"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
//import * as functions from 'firebase-functions';
const admin = require("firebase-admin");
admin.initializeApp();
const getFromFirebase = require("./get-from-db-storage");
const sendMail_Noti = require("./sendMailAndNoti");
const once_a_day = require("./once-a-day");
const auth = require("./auth");
// admin.initializeApp(functions.config().firebase);
//export const im_ex = import_export.getAllPatientsDataInCSV;
exports.getMipuysForPatient = getFromFirebase.getMipuysForPatient;
exports.getOneMipuyByDateAndId = getFromFirebase.getOneMipuyByDateAndId;
exports.getPatByDiffi = getFromFirebase.getPatientListByDiffiInLastMipuy;
//export const getMainDiffiAreas = getFromFirebase.getMainDiffiAreas;
exports.sendMail3 = sendMail_Noti.sendWelcomeEmailFunc2;
exports.onceADay = once_a_day.do_once_a_day;
exports.onceAWeek = once_a_day.do_once_a_week;
//export const MLFunc = ML.MLFunction;
exports.login = auth.login;
//# sourceMappingURL=index.js.map