"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
//import * as functions from 'firebase-functions';
const admin = require("firebase-admin");
admin.initializeApp();
const getFromFirebase = require("./get-from-db-storage");
//import * as sendMail_Noti from './sendMailAndNoti';
//import * as ML from './ML';
//import {find} from 'p-iteration';
//import * as import_export from './exports_imports_data';
const massages = require("./massages");
//export const getMipuysForPatient = getFromFirebase.getMipuysForPatient;
exports.getOneMipuyByDateAndId = getFromFirebase.getOneMipuyByDateAndId;
exports.getPatByDiffi = getFromFirebase.getPatientListByDiffiInLastMipuy;
//export const getSecondCategories = getFromFirebase.getSecondCategories;
//export const sendMail3 = sendMail_Noti.sendWelcomeEmailFunc2;
exports.onceADay = massages.do_once_a_day;
exports.onceAWeek = massages.do_once_a_week;
//export const MLsendDate = ML.sendData;
//export const login = auth.login;
exports.getMipuysForPatientBySecondAreas = getFromFirebase.getMipuysForPatientBySecond;
//# sourceMappingURL=index.js.map