"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
//import * as functions from 'firebase-functions';
const admin = require("firebase-admin");
admin.initializeApp();
const getFromFirebase = require("./get-from-db-storage");
const sendMail_Noti = require("./sendMailAndNoti");
const ML = require("./ML");
const massages = require("./massages");
const auth = require("./auth");
// admin.initializeApp(functions.config().firebase);
//export const im_ex = import_export.getAllPatientsDataInCSV;
exports.getMipuysForPatient = getFromFirebase.getMipuysForPatient;
exports.getOneMipuyByDateAndId = getFromFirebase.getOneMipuyByDateAndId;
exports.getPatByDiffi = getFromFirebase.getPatientListByDiffiInLastMipuy;
exports.getSecondCategories = getFromFirebase.getSecondCategories;
exports.sendMail3 = sendMail_Noti.sendWelcomeEmailFunc2;
exports.onceADay = massages.do_once_a_day;
exports.onceAWeek = massages.do_once_a_week;
exports.MLsendDate = ML.sendData;
exports.login = auth.login;
exports.getMipuysForPatientBySecondAreas = getFromFirebase.getMipuysForPatientBySecond;
//# sourceMappingURL=index.js.map